### ISSUE TITLE
Size of the storage

### ISSUE THREAD

**Issue by LuizFellype** [carlcraig/react-native-key-value-store#5]
I am looking for key-value stores because the  AsyncStorage has 6mb limitation for Android. This is a package that get better in this point, or also has this limitation?

**Comment by carlcraig** [comment]
This library utilises `AsyncStorage`, so you will have all the same limitations.

There are [ways](https://github.com/facebook/react-native/issues/3387) to increase the size of storage on android.

If you are using lots of storage, you will most likely be better off using a database like [Realm](https://realm.io/docs/javascript/latest) or [sqlite](https://github.com/andpor/react-native-sqlite-storage).
